enum {
    // rise frames
    FRAME_rise1,
    FRAME_rise2,
    FRAME_rise3,
    FRAME_rise4,
    FRAME_rise5,
    FRAME_rise6,
    FRAME_rise7,
    FRAME_rise8,
    FRAME_rise9,
    FRAME_rise10,
    FRAME_rise11,
    FRAME_rise12,
    FRAME_rise13,
    FRAME_rise14,
    FRAME_rise15,
    FRAME_rise16,
    FRAME_rise17,

    // walk/idle frames
    FRAME_walk1,
    FRAME_walk2,
    FRAME_walk3,
    FRAME_walk4,
    FRAME_walk5,
    FRAME_walk6,
    FRAME_walk7,
    FRAME_walk8,
    FRAME_walk9,
    FRAME_walk10,
    FRAME_walk11,
    FRAME_walk12,
    FRAME_walk13,
    FRAME_walk14,
    FRAME_walk15,
    FRAME_walk16,
    FRAME_walk17,
    FRAME_walk18,
    FRAME_walk19,
    FRAME_walk20,
    FRAME_walk21,
    FRAME_walk22,
    FRAME_walk23,
    FRAME_walk24,
    FRAME_walk25,
    FRAME_walk26,
    FRAME_walk27,
    FRAME_walk28,
    FRAME_walk29,
    FRAME_walk30,
    FRAME_walk31,

    // death frames
    FRAME_death1,
    FRAME_death2,
    FRAME_death3,
    FRAME_death4,
    FRAME_death5,
    FRAME_death6,
    FRAME_death7,
    FRAME_death8,
    FRAME_death9,

    // attack frames
    FRAME_attack1,
    FRAME_attack2,
    FRAME_attack3,
    FRAME_attack4,
    FRAME_attack5,
    FRAME_attack6,
    FRAME_attack7,
    FRAME_attack8,
    FRAME_attack9,
    FRAME_attack10,
    FRAME_attack11,
    FRAME_attack12,
    FRAME_attack13,
    FRAME_attack14,
    FRAME_attack15,
    FRAME_attack16,
    FRAME_attack17,
    FRAME_attack18,
    FRAME_attack19,
    FRAME_attack20,
    FRAME_attack21,
    FRAME_attack22,
    FRAME_attack23,

    // shock A frames
    FRAME_shocka1,
    FRAME_shocka2,
    FRAME_shocka3,
    FRAME_shocka4,
    FRAME_shocka5,
    FRAME_shocka6,
    FRAME_shocka7,
    FRAME_shocka8,
    FRAME_shocka9,
    FRAME_shocka10,

    // shock B frames
    FRAME_shockb1,
    FRAME_shockb2,
    FRAME_shockb3,
    FRAME_shockb4,
    FRAME_shockb5,
    FRAME_shockb6,
    FRAME_shockb7,
    FRAME_shockb8,
    FRAME_shockb9,
    FRAME_shockb10,

    // shock C frames
    FRAME_shockc1,
    FRAME_shockc2,
    FRAME_shockc3,
    FRAME_shockc4,
    FRAME_shockc5,
    FRAME_shockc6,
    FRAME_shockc7,
    FRAME_shockc8,
    FRAME_shockc9,
    FRAME_shockc10
};

#define MODEL_SCALE 1.000000f
