// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// G:\quake2\baseq2\models/monsters/tank

// This file generated by qdata - Do NOT Modify

enum {
    FRAME_attack01,
    FRAME_attack02,
    FRAME_attack03,
    FRAME_attack04,
    FRAME_attack05,
    FRAME_attack06,
    FRAME_attack07,
    FRAME_attack08,
    FRAME_attack09,
    FRAME_attack10,
    FRAME_attack11,
    FRAME_pain01,
    FRAME_pain02,
    FRAME_pain03,
    FRAME_pain04,
    FRAME_pain05,
    FRAME_death01,
    FRAME_death02,
    FRAME_death03,
    FRAME_death04,
    FRAME_death05,
    FRAME_death06,
    FRAME_death07,
    FRAME_walk01,
    FRAME_walk02,
    FRAME_walk03,
    FRAME_walk04,
    FRAME_walk05,
    FRAME_walk06,
    FRAME_walk07,
    FRAME_walk08,
    FRAME_walk09,
    FRAME_walk10,
    FRAME_walk11,
    FRAME_walk12
};

#define MODEL_SCALE 1.000000f
