// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
// models/quake1/tarbaby/tris.md2
//
// This file generated by qdata - Do NOT Modify

enum {
    // stand frames (0..0)
    FRAME_stand1 = 0,

    // run frames (25..49)
    FRAME_run1 = 25,
    FRAME_run2,
    FRAME_run3,
    FRAME_run4,
    FRAME_run5,
    FRAME_run6,
    FRAME_run7,
    FRAME_run8,
    FRAME_run9,
    FRAME_run10,
    FRAME_run11,
    FRAME_run12,
    FRAME_run13,
    FRAME_run14,
    FRAME_run15,
    FRAME_run16,
    FRAME_run17,
    FRAME_run18,
    FRAME_run19,
    FRAME_run20,
    FRAME_run21,
    FRAME_run22,
    FRAME_run23,
    FRAME_run24,
    FRAME_run25,

    // jump frames (50..55)
    FRAME_jump1 = 50,
    FRAME_jump2,
    FRAME_jump3,
    FRAME_jump4,
    FRAME_jump5,
    FRAME_jump6,

    // fly frames (56..59)
    FRAME_fly1 = 56,
    FRAME_fly2,
    FRAME_fly3,
    FRAME_fly4,

    // death frames (60..60)
    FRAME_death1 = 60
};

#define MODEL_SCALE 1.000000f
